'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE='jorgefit-v3-data';
const nowISO=()=>new Date().toISOString();
const defaultState={profile:null,settings:{duration:60,days:6,jointFriendly:true},workouts:[],measurements:[],recovery:{Chest:92,Back:76,Shoulders:84,Arms:68,Legs:88,Core:95},exerciseHistory:{},coachNotes:[],currentPlan:null};
let state=loadState(), timerId=null, elapsed=0, restId=null, restSeconds=90, deferredInstall=null;
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORE)||'{}');return {...structuredClone(defaultState),...saved,exerciseHistory:saved.exerciseHistory||{},coachNotes:saved.coachNotes||[]}}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORE,JSON.stringify(state))}

const muscleDatabase={
 Chest:{image:'chest.png',stretch:'Doorway chest stretch',hold:'20–30 sec per side'},Back:{image:'back.png',stretch:'Child’s pose or lat stretch',hold:'20–30 sec'},Shoulders:{image:'shoulders.png',stretch:'Cross-body shoulder stretch',hold:'20–30 sec per side'},'Rear delts':{image:'shoulders.png',stretch:'Cross-body rear-delt stretch',hold:'20–30 sec per side'},Biceps:{image:'biceps.png',stretch:'Wall biceps stretch',hold:'20–30 sec per side'},Triceps:{image:'triceps.png',stretch:'Overhead triceps stretch',hold:'20–30 sec per side'},Core:{image:'core.png',stretch:'Cobra stretch with gentle breathing',hold:'15–20 sec'},Legs:{image:'quadriceps.png',stretch:'Quad and hamstring cooldown',hold:'20–30 sec each'},Quads:{image:'quadriceps.png',stretch:'Standing quadriceps stretch',hold:'20–30 sec per side'},Hamstrings:{image:'hamstrings.png',stretch:'Seated hamstring stretch',hold:'20–30 sec per side'},Glutes:{image:'glutes.png',stretch:'Figure-four glute stretch',hold:'20–30 sec per side'},Calves:{image:'calves.png',stretch:'Wall calf stretch',hold:'20–30 sec per side'},Cardio:{image:'cardio.png',stretch:'Full-body cooldown mobility',hold:'3–5 minutes'},Custom:{image:'full-body.png',stretch:'Gentle full-body stretch',hold:'20–30 sec'}};
function muscleInfo(name){return muscleDatabase[name]||muscleDatabase.Custom}
function muscleCoachPanel(e){const m=muscleInfo(e.muscle);return `<div class="muscle-coach-panel"><img src="./${m.image}" alt="${e.muscle} muscle group" onerror="this.onerror=null;this.src='./full-body.png'"><div><span>Muscle group working</span><strong>${e.muscle}</strong><p>After this exercise: ${m.stretch} · ${m.hold}. Breathe slowly and never bounce.</p></div></div>`}

const library={
 push:[['Machine Chest Press','Chest','3','8-12','Keep shoulder blades back.'],['Incline Dumbbell Press','Chest','3','8-12','Use neutral grip if shoulders feel tight.'],['Pec Deck','Chest','3','12-15','Controlled stretch.'],['Machine Shoulder Press','Shoulders','3','8-12','Back supported.'],['Cable Lateral Raise','Shoulders','3','12-15','Light and controlled.'],['Rope Pressdown','Triceps','3','10-15','Elbows fixed.'],['Cable Overhead Extension','Triceps','2','12-15','Stop if elbows hurt.']],
 pull:[['Neutral-Grip Lat Pulldown','Back','3','8-12','Pull toward upper chest.'],['Chest-Supported Row','Back','3','8-12','No lower-back loading.'],['Single-Arm Cable Row','Back','3','10-12','Brace your core.'],['Reverse Pec Deck','Rear delts','3','12-15','Do not shrug.'],['Face Pull','Shoulders','2','12-15','Pull toward forehead.'],['Machine Preacher Curl','Biceps','3','10-12','Slow lowering.'],['Rope Hammer Curl','Biceps','2','12-15','Neutral wrist.']],
 legs:[['Seated Leg Press','Legs','3','10-15','Use pain-free depth; do not lock knees.'],['Seated Leg Curl','Hamstrings','3','10-15','Pause at contraction.'],['Leg Extension','Quads','2','12-15','Light load and pain-free range.'],['Hip Abduction Machine','Glutes','3','12-20','Controlled reps.'],['Glute Bridge Machine','Glutes','3','10-15','Keep ribs down.'],['Seated Calf Raise','Calves','3','12-20','Full comfortable range.'],['Pallof Press','Core','3','10/side','Resist rotation.']],
 upper:[['Machine Chest Press','Chest','3','8-12','Back supported.'],['Neutral-Grip Lat Pulldown','Back','3','8-12','Smooth reps.'],['Chest-Supported Row','Back','3','10-12','No swinging.'],['Machine Shoulder Press','Shoulders','3','8-12','Pain-free range.'],['Pec Deck','Chest','2','12-15','Controlled stretch.'],['Rope Pressdown','Triceps','2','10-15','Elbows fixed.'],['Machine Preacher Curl','Biceps','2','10-15','Slow lowering.']],
 full:[['Seated Leg Press','Legs','3','10-15','Pain-free depth.'],['Machine Chest Press','Chest','3','8-12','Back supported.'],['Neutral-Grip Lat Pulldown','Back','3','8-12','No swinging.'],['Seated Leg Curl','Hamstrings','3','10-15','Pause at contraction.'],['Machine Shoulder Press','Shoulders','2','10-12','Easy on back.'],['Cable Row','Back','2','10-12','Brace core.'],['Pallof Press','Core','3','10/side','Resist rotation.']],
 cardio:[['Treadmill Walk','Cardio','1','15 min','Comfortable incline; hold rails only if needed.'],['Recumbent Bike','Cardio','1','15 min','Moderate pace.'],['Cable Wood Chop','Core','3','10/side','Rotate through upper body gently.'],['Pallof Press','Core','3','10/side','Keep hips square.'],['Dead Bug','Core','3','8/side','Keep lower back supported.']]
};

const exerciseDetails={
'Machine Chest Press':{image:'machine-chest-press.svg',equipment:'Chest press machine',instructions:'Adjust the seat so the handles line up with mid-chest. Keep your shoulder blades against the pad and press without locking your elbows.',replacements:['Incline Dumbbell Press','Cable Chest Press','Smith Machine Bench Press','Push-Up']},
'Incline Dumbbell Press':{image:'incline-dumbbell-press.svg',equipment:'Dumbbells + incline bench',instructions:'Set the bench to a low incline. Keep wrists stacked over elbows and lower the dumbbells under control.',replacements:['Machine Chest Press','Smith Machine Incline Press','Cable Chest Press','Push-Up']},
'Pec Deck':{image:'pec-deck.svg',equipment:'Pec deck machine',instructions:'Keep your chest lifted and elbows slightly bent. Bring the pads together without letting your shoulders roll forward.',replacements:['Cable Fly','Dumbbell Fly','Machine Chest Press','Push-Up']},
'Machine Shoulder Press':{image:'machine-shoulder-press.svg',equipment:'Shoulder press machine',instructions:'Keep your back supported and ribs down. Press through a comfortable range without shrugging.',replacements:['Seated Dumbbell Press','Landmine Press','Cable Shoulder Press','Incline Chest Press']},
'Cable Lateral Raise':{image:'cable-lateral-raise.svg',equipment:'Cable station',instructions:'Raise the arm slightly forward of your body. Use a light load and stop around shoulder height.',replacements:['Dumbbell Lateral Raise','Lateral Raise Machine','Resistance Band Lateral Raise']},
'Rope Pressdown':{image:'rope-pressdown.svg',equipment:'Cable station + rope',instructions:'Keep elbows beside your ribs. Extend fully and separate the rope slightly at the bottom.',replacements:['Straight-Bar Pressdown','Assisted Dip','Close-Grip Push-Up','Dumbbell Kickback']},
'Cable Overhead Extension':{image:'cable-overhead-extension.svg',equipment:'Cable station + rope',instructions:'Brace your core and keep your elbows pointing forward. Extend without arching your lower back.',replacements:['Dumbbell Overhead Extension','Rope Pressdown','Machine Triceps Extension']},
'Neutral-Grip Lat Pulldown':{image:'neutral-lat-pulldown-ai.png',stepsImage:'neutral-lat-pulldown-steps-ai.png',mistakesImage:'neutral-lat-pulldown-mistakes-ai.png',equipment:'Cable lat-pulldown machine with neutral handles',muscles:'Lats · Biceps · Teres major · Rhomboids · Rear delts',instructions:'1. Secure your thighs under the pads. 2. Grip the neutral handles with palms facing each other. 3. Keep your chest tall and shoulders down. 4. Pull your elbows toward your pockets until the handles reach your upper chest. 5. Pause, then return slowly for 2–3 seconds.',mistakes:'Leaning too far back; using momentum; pulling only halfway; shrugging the shoulders; letting the weight stack slam.',replacements:['Assisted Pull-Up','Single-Arm Cable Pulldown','Chest-Supported Row','Resistance Band Pulldown']},
'Chest-Supported Row':{image:'chest-supported-row.svg',equipment:'Row machine or incline bench',instructions:'Keep your chest against the pad. Pull elbows behind you and pause before lowering slowly.',replacements:['Seated Cable Row','Single-Arm Cable Row','Machine High Row','Dumbbell Row']},
'Single-Arm Cable Row':{image:'single-arm-cable-row.svg',equipment:'Cable station',instructions:'Stay square to the cable and pull your elbow toward your hip. Do not twist through the lower back.',replacements:['Seated Cable Row','Chest-Supported Row','Dumbbell Row','Machine Row']},
'Cable Row':{image:'cable-row.svg',equipment:'Seated cable row',instructions:'Brace your torso and pull toward your lower ribs. Keep the movement smooth and controlled.',replacements:['Chest-Supported Row','Machine Row','Single-Arm Cable Row','Dumbbell Row']},
'Reverse Pec Deck':{image:'reverse-pec-deck.svg',equipment:'Reverse pec deck',instructions:'Keep your chest against the pad and move your arms outward without shrugging.',replacements:['Face Pull','Cable Reverse Fly','Bent-Over Dumbbell Reverse Fly']},
'Face Pull':{image:'face-pull.svg',equipment:'Cable station + rope',instructions:'Pull the rope toward eyebrow level and rotate your hands apart. Keep ribs down.',replacements:['Reverse Pec Deck','Cable Reverse Fly','Resistance Band Face Pull']},
'Machine Preacher Curl':{image:'preacher-curl.svg',equipment:'Preacher curl machine',instructions:'Keep your upper arms on the pad. Curl smoothly and lower slowly without fully snapping the elbows straight.',replacements:['Cable Curl','Dumbbell Preacher Curl','Seated Dumbbell Curl','Machine Curl']},
'Rope Hammer Curl':{image:'rope-hammer-curl.svg',equipment:'Cable station + rope',instructions:'Keep wrists neutral and elbows still. Curl the rope without swinging your torso.',replacements:['Dumbbell Hammer Curl','Cable Curl','Machine Curl']},
'Seated Leg Press':{image:'seated-leg-press.svg',equipment:'Leg press machine',instructions:'Place feet securely on the platform. Lower only as far as comfortable and never lock your knees.',replacements:['Hack Squat Machine','Goblet Squat','Smith Machine Squat','Step-Up']},
'Seated Leg Curl':{image:'seated-leg-curl.svg',equipment:'Seated leg curl machine',instructions:'Align your knees with the machine pivot. Curl through a comfortable range and pause briefly.',replacements:['Lying Leg Curl','Romanian Deadlift','Cable Leg Curl','Stability-Ball Curl']},
'Leg Extension':{image:'leg-extension.svg',equipment:'Leg extension machine',instructions:'Align knees with the machine pivot. Use a light load and a pain-free range.',replacements:['Spanish Squat','Step-Up','Wall Sit','Goblet Squat']},
'Hip Abduction Machine':{image:'hip-abduction.svg',equipment:'Hip abduction machine',instructions:'Sit tall and open your knees under control. Avoid bouncing or leaning excessively.',replacements:['Cable Hip Abduction','Resistance Band Side Steps','Side-Lying Leg Raise']},
'Glute Bridge Machine':{image:'glute-bridge.svg',equipment:'Glute drive machine',instructions:'Keep ribs down and drive through your heels. Finish by squeezing your glutes, not arching your back.',replacements:['Hip Thrust','Floor Glute Bridge','Cable Pull-Through','Smith Machine Hip Thrust']},
'Seated Calf Raise':{image:'seated-calf-raise.svg',equipment:'Seated calf machine',instructions:'Lower your heels comfortably, then rise onto the balls of your feet and pause at the top.',replacements:['Standing Calf Raise','Leg Press Calf Raise','Single-Leg Calf Raise']},
'Pallof Press':{image:'pallof-press.svg',equipment:'Cable station or resistance band',instructions:'Stand sideways to the cable, brace your core, and press straight out without rotating.',replacements:['Cable Hold','Dead Bug','Bird Dog','Plank']},
'Treadmill Walk':{image:'treadmill-walk.svg',equipment:'Treadmill',instructions:'Walk at a pace that allows steady breathing. Use a comfortable incline and upright posture.',replacements:['Elliptical','Recumbent Bike','Indoor Track Walk','Step Machine']},
'Recumbent Bike':{image:'recumbent-bike.svg',equipment:'Recumbent bike',instructions:'Adjust the seat so the knee remains slightly bent at full extension. Pedal smoothly.',replacements:['Upright Bike','Treadmill Walk','Elliptical','Arm Ergometer']},
'Cable Wood Chop':{image:'cable-wood-chop.svg',equipment:'Cable station',instructions:'Brace your core and move the handle diagonally with controlled torso rotation.',replacements:['Pallof Press','Medicine Ball Chop','Resistance Band Wood Chop','Dead Bug']},
'Dead Bug':{image:'dead-bug.svg',equipment:'Exercise mat',instructions:'Keep your lower back gently supported against the floor while extending opposite arm and leg.',replacements:['Bird Dog','Pallof Press','Heel Tap','Plank']}
};
const genericDetail={image:'generic-exercise.svg',equipment:'Gym equipment',instructions:'Use a controlled, pain-free range of motion. Stop if you feel sharp pain.',replacements:[]};
function detailFor(name){return exerciseDetails[name]||genericDetail}
function imagePath(name){const img=detailFor(name).image;return img.startsWith('assets/')?`./${img}`:`./${img}`}
function hydrateExercise(e){const d=detailFor(e.name);const sets=Number(e.sets)||3;return {...e,image:e.image||d.image,equipment:e.equipment||d.equipment,instructions:e.instructions||d.instructions,replacements:e.replacements?.length?e.replacements:d.replacements,logged:e.logged?.length?e.logged:Array.from({length:sets},()=>({weight:'',reps:'',done:false,rpe:null}))}}

function exerciseObj(x){return hydrateExercise({name:x[0],muscle:x[1],sets:Number(x[2]),reps:x[3],note:x[4],logged:Array.from({length:Number(x[2])},()=>({weight:'',reps:'',done:false}))})}
function smartFocus(){const lowest=Object.entries(state.recovery).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);if(lowest.includes('Legs')&&state.recovery.Legs>80)return 'legs';const recent=state.workouts[0]?.focus;if(recent==='push')return 'pull';if(recent==='pull')return 'legs';return 'upper'}
function buildPlan(focus='auto',minutes=state.settings.duration,energy=7){if(focus==='auto')focus=smartFocus();let base=(library[focus]||library.upper).map(exerciseObj);let count=minutes<=30?4:minutes<=45?5:minutes<=60?7:8;if(energy<=4)count=Math.max(4,count-1);base=base.slice(0,count);const names={push:'Push Day',pull:'Pull Day',legs:'Joint-Friendly Legs',upper:'Upper Body Power',full:'Full Body Strength',cardio:'Cardio + Core'};return {id:crypto.randomUUID?.()||Date.now().toString(),title:names[focus],focus,minutes:Number(minutes),energy:Number(energy),created:nowISO(),exercises:base}}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));scrollTo({top:0,behavior:'smooth'})}
function renderHome(){const h=new Date().getHours();$('#greeting').textContent=`Good ${h<12?'morning':h<18?'afternoon':'evening'}, ${state.profile?.name||'Jorge'}`;$('#todayLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});if(!state.currentPlan)state.currentPlan=buildPlan();const p=state.currentPlan;$('#todayWorkoutName').textContent=p.title;$('#todayWorkoutFocus').textContent=[...new Set(p.exercises.map(e=>e.muscle))].join(' · ');$('#exerciseCount').textContent=p.exercises.length;$('#durationCount').textContent=p.minutes;$('#calorieEstimate').textContent=Math.round(p.minutes*(p.focus==='cardio'?7:8));const readiness=Math.round(Object.values(state.recovery).reduce((a,b)=>a+b,0)/Object.keys(state.recovery).length);$('#readinessBadge').textContent=`Ready ${readiness}%`;$('#coachMessage').textContent=coachText(readiness,p);$('#recoveryGrid').innerHTML=Object.entries(state.recovery).map(([m,v])=>`<div class="recovery-item"><div class="row"><strong>${m}</strong><span>${v}%</span></div><div class="bar"><i style="width:${v}%"></i></div></div>`).join('');renderWeek();saveState()}
function coachText(r,p){if(r<60)return 'Recovery is low today. Use lighter weights, stop 2–3 reps before failure, and choose a 30–45 minute session.';if(p.focus==='legs')return 'Your lower body is ready. Today’s plan avoids heavy spinal loading and uses controlled, knee-friendly machine work.';return `Your recovery supports ${p.title}. Start with a weight you can control for every rep. When all sets reach the top of the rep range, increase the load by the smallest amount next time.`}
function renderWeek(){const start=new Date();start.setDate(start.getDate()-start.getDay());start.setHours(0,0,0,0);const wk=state.workouts.filter(w=>new Date(w.date)>=start);$('#weekWorkouts').textContent=wk.length;$('#weekMinutes').textContent=wk.reduce((a,w)=>a+w.minutes,0);$('#weekVolume').textContent=Math.round(wk.reduce((a,w)=>a+(w.volume||0),0)).toLocaleString();$('#streakCount').textContent=calculateStreak();const end=new Date(start);end.setDate(end.getDate()+6);$('#weekRange').textContent=`${start.toLocaleDateString(undefined,{month:'short',day:'numeric'})}–${end.toLocaleDateString(undefined,{month:'short',day:'numeric'})}`}
function calculateStreak(){const days=new Set(state.workouts.map(w=>new Date(w.date).toDateString()));let d=new Date(),n=0;if(!days.has(d.toDateString()))d.setDate(d.getDate()-1);while(days.has(d.toDateString())){n++;d.setDate(d.getDate()-1)}return n}
function difficultyFor(e){const n=(e.name||'').toLowerCase();return /deadlift|squat|bulgarian|overhead/.test(n)?'Intermediate':'Beginner friendly'}
function equipmentFor(e){const n=(e.name||'').toLowerCase();if(/dumbbell/.test(n))return 'Dumbbells';if(/cable|rope|pallof|wood chop|face pull/.test(n))return 'Cable';if(/bike|treadmill/.test(n))return 'Cardio';if(/bridge|dead bug/.test(n))return 'Bodyweight';return 'Machine'}
function exerciseBadges(e){return `<div class="exercise-badges"><span>${e.muscle}</span><span>${difficultyFor(e)}</span><span>${equipmentFor(e)}</span></div>`}
function renderPlan(plan=state.currentPlan){if(!plan)return;plan.exercises=plan.exercises.map(hydrateExercise);$('#generatedTitle').textContent=plan.title;$('#generatedMeta').textContent=`${plan.exercises.length} exercises · ${plan.minutes} min`;$('#generatedExerciseList').innerHTML=plan.exercises.map((e,i)=>`<article class="plan-exercise-card"><div class="exercise-preview-row"><img src="${imagePath(e.name)}" alt="${e.name} exercise illustration"><div><strong>${i+1}. ${e.name}</strong><span>${e.sets} sets × ${e.reps} · about ${Math.max(4,e.sets*2)} min</span>${exerciseBadges(e)}</div></div>${muscleCoachPanel(e)}<div class="plan-exercise-buttons"><button class="how-to-btn" data-plan-info="${i}">How to do it</button><button class="machine-down-btn" data-plan-replace="${i}">⚠ Machine unavailable</button></div></article>`).join('');$$('[data-plan-info]').forEach(b=>b.onclick=()=>openExerciseInfo(Number(b.dataset.planInfo)));$$('[data-plan-replace]').forEach(b=>b.onclick=()=>openReplacement(Number(b.dataset.planReplace)))}
function startWorkout(plan){state.currentPlan=structuredClone(plan);elapsed=0;$('#activeWorkoutTitle').textContent=plan.title;renderActive();showView('workoutView');clearInterval(timerId);timerId=setInterval(()=>{elapsed++;$('#workoutTimer').textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`},1000)}
function historyFor(name){
  const raw=state.exerciseHistory?.[name];
  if(!raw)return [];
  if(Array.isArray(raw))return raw;
  if(Array.isArray(raw.sessions))return raw.sessions;
  return raw.weight!=null?[raw]:[];
}
function previousFor(name){return historyFor(name)[0]||null}
function repRange(reps){const nums=String(reps||'').match(/\d+/g)?.map(Number)||[];return {min:nums[0]||8,max:nums[1]||nums[0]||12}}
function loadIncrement(e){return /Legs|Hamstrings|Quads|Glutes|Calves/i.test(e.muscle||'')?10:5}
function roundToFive(v){return Math.max(5,Math.round(v/5)*5)}
function weightRecommendation(e){
  const h=previousFor(e.name);
  if(!h||!Number(h.weight))return {weight:null,last:'Not tracked',reason:'Use a light weight you can control for every rep. Finish with about 2–3 good reps still available.'};
  const {max}=repRange(e.reps), inc=loadIncrement(e), effort=h.lastRpe||h.rpe||'right';
  let weight=Number(h.weight), reason='Repeat the same weight and improve rep quality.';
  if(effort==='easy'){weight=roundToFive(weight+inc);reason=`Last session felt easy, so increase by ${inc} lb while keeping clean form.`}
  else if(effort==='hard'||effort==='failed'){weight=roundToFive(weight*.95);reason='The last effort was too hard. Reduce about 5% and rebuild with controlled reps.'}
  else if(Number(h.reps)>=max){weight=roundToFive(weight+inc);reason=`You reached the top of the ${e.reps} rep range. Progress by ${inc} lb.`}
  else{reason=`Stay at ${weight} lb and work toward ${max} clean reps before increasing.`}
  return {weight,last:`${h.weight} lb × ${h.reps} reps`,reason};
}
function coachSuggestion(e){const r=weightRecommendation(e);return r.weight?`Recommended today: ${r.weight} lb. ${r.reason}`:`Starting-weight check: ${r.reason}`}
function renderActive(){const p=state.currentPlan;p.exercises=p.exercises.map(hydrateExercise);$('#activeExerciseList').innerHTML=p.exercises.map((e,ei)=>{const rec=weightRecommendation(e);return `<article class="exercise-card ${e.logged.every(s=>s.done)?'done':''}"><div class="exercise-visual"><img src="${imagePath(e.name)}" alt="${e.name} exercise guide" loading="lazy"><div><h3>${ei+1}. ${e.name}</h3><div class="exercise-note">Target ${e.reps} reps · about ${Math.max(4,e.sets*2)} min</div>${exerciseBadges(e)}<button class="how-to-btn" data-info="${ei}">View exercise guide</button></div></div>${muscleCoachPanel(e)}<div class="smart-weight-card"><div><span>Last performance</span><strong>${rec.last}</strong></div><div><span>AI recommended weight</span><strong>${rec.weight?`${rec.weight} lb`:'Starting test'}</strong></div><p>${rec.reason}</p>${rec.weight?`<button data-use-rec="${ei}" class="use-weight-btn">Use ${rec.weight} lb for all sets</button>`:''}</div><p class="exercise-tip">Coach cue: ${e.note}</p>${e.logged.map((s,si)=>`<div class="set-row"><strong>${si+1}</strong><input inputmode="decimal" placeholder="lb" value="${s.weight}" data-e="${ei}" data-s="${si}" data-f="weight"><input inputmode="numeric" placeholder="reps" value="${s.reps}" data-e="${ei}" data-s="${si}" data-f="reps"><button class="${s.done?'completed':''}" data-complete="${ei}-${si}">✓</button></div><div class="effort-row"><span>How did this set feel?</span><button data-rpe="${ei}-${si}-easy" class="${s.rpe==='easy'?'selected':''}">Too easy</button><button data-rpe="${ei}-${si}-right" class="${s.rpe==='right'?'selected':''}">Good</button><button data-rpe="${ei}-${si}-hard" class="${s.rpe==='hard'?'selected':''}">Hard</button><button data-rpe="${ei}-${si}-failed" class="${s.rpe==='failed'?'selected':''}">Failed</button></div>`).join('')}<button class="machine-down-btn" data-replace="${ei}">⚠ Machine busy or unavailable</button><div class="exercise-actions"><button class="text-btn" data-addset="${ei}">+ Set</button><button class="text-btn" data-remove="${ei}">Remove</button></div></article>`}).join('');bindActive();$$('[data-rpe]').forEach(b=>b.onclick=()=>{const [ei,si,rpe]=b.dataset.rpe.split('-');state.currentPlan.exercises[ei].logged[si].rpe=rpe;saveState();renderActive()});$$('[data-use-rec]').forEach(b=>b.onclick=()=>{const ei=Number(b.dataset.useRec),e=state.currentPlan.exercises[ei],rec=weightRecommendation(e);e.logged.forEach(s=>{if(!s.weight)s.weight=rec.weight});saveState();renderActive()});updateProgress()}
function bindActive(){$$('#activeExerciseList input').forEach(i=>i.oninput=()=>{state.currentPlan.exercises[i.dataset.e].logged[i.dataset.s][i.dataset.f]=i.value;saveState()});$$('[data-complete]').forEach(b=>b.onclick=()=>{const [e,s]=b.dataset.complete.split('-').map(Number);const set=state.currentPlan.exercises[e].logged[s];set.done=!set.done;saveState();renderActive();if(set.done)startRest()});$$('[data-addset]').forEach(b=>b.onclick=()=>{state.currentPlan.exercises[b.dataset.addset].logged.push({weight:'',reps:'',done:false});renderActive();saveState()});$$('[data-remove]').forEach(b=>b.onclick=()=>{state.currentPlan.exercises.splice(b.dataset.remove,1);renderActive();saveState()});$$('[data-replace]').forEach(b=>b.onclick=()=>openReplacement(Number(b.dataset.replace)));$$('[data-info]').forEach(b=>b.onclick=()=>openExerciseInfo(Number(b.dataset.info)))}
function openExerciseInfo(index){const e=hydrateExercise(state.currentPlan.exercises[index]),d=detailFor(e.name),rec=weightRecommendation(e);$('#exerciseInfoImage').src=imagePath(e.name);$('#exerciseInfoImage').alt=`${e.name} exercise guide`;$('#exerciseInfoTitle').textContent=e.name;$('#exerciseInfoLast').textContent=rec.last;$('#exerciseInfoRecommended').textContent=rec.weight?`${rec.weight} lb`:'Find starting weight';$('#exerciseInfoReason').textContent=rec.reason;$('#exerciseInfoEquipment').textContent=e.equipment;$('#exerciseInfoMuscles').textContent=d.muscles||`${e.muscle} and supporting muscles`;$('#exerciseInfoInstructions').textContent=e.instructions;$('#exerciseInfoMistakes').textContent=d.mistakes||'Avoid momentum, shortened range of motion, and any position that causes sharp pain.';$('#exerciseInfoTip').textContent=e.note;const steps=$('#exerciseInfoStepsImage'),mistakes=$('#exerciseInfoMistakesImage');steps.hidden=!d.stepsImage;if(d.stepsImage)steps.src=`./${d.stepsImage}`;mistakes.hidden=!d.mistakesImage;if(d.mistakesImage)mistakes.src=`./${d.mistakesImage}`;$('#exerciseInfoDialog').showModal()}
let replacementIndex=null;
function openReplacement(index){replacementIndex=index;const e=hydrateExercise(state.currentPlan.exercises[index]);$('#replacementOriginal').textContent=`Replace ${e.name}`;const options=e.replacements?.length?e.replacements:['Custom Exercise'];$('#replacementList').innerHTML=options.map(name=>{const d=detailFor(name);return `<button class="replacement-option" data-choice="${name}"><img src="${imagePath(name)}" alt=""><span><strong>${name}</strong><small>${d.equipment}</small></span><b>Use</b></button>`}).join('');$$('[data-choice]').forEach(b=>b.onclick=()=>replaceExercise(b.dataset.choice));$('#replacementDialog').showModal()}
function replaceExercise(name){if(replacementIndex==null)return;const old=state.currentPlan.exercises[replacementIndex];const d=detailFor(name);state.currentPlan.exercises[replacementIndex]=hydrateExercise({name,muscle:old.muscle,sets:old.sets,reps:old.reps,note:d.instructions.split('.')[0]+'.',logged:old.logged.map(s=>({...s,done:false}))});saveState();$('#replacementDialog').close();renderAll();if($('#workoutView').classList.contains('active'))renderActive()}
function updateProgress(){const sets=state.currentPlan.exercises.flatMap(e=>e.logged),done=sets.filter(s=>s.done).length;$('#workoutProgress').style.width=`${sets.length?done/sets.length*100:0}%`}
function startRest(){restSeconds=90;updateRest();$('#restDialog').showModal();clearInterval(restId);restId=setInterval(()=>{restSeconds--;updateRest();if(restSeconds<=0){clearInterval(restId);$('#restDialog').close();navigator.vibrate?.([200,100,200])}},1000)}
function updateRest(){$('#restTime').textContent=`${String(Math.floor(restSeconds/60)).padStart(2,'0')}:${String(restSeconds%60).padStart(2,'0')}`}
function finishWorkout(){clearInterval(timerId);const p=state.currentPlan;let volume=0,completedSets=0,prs=[];p.exercises.forEach(e=>{const completed=e.logged.filter(s=>s.done);completed.forEach(s=>{volume+=(Number(s.weight)||0)*(Number(s.reps)||0);completedSets++});if(completed.length){const best=completed.reduce((a,b)=>(Number(b.weight)||0)>(Number(a.weight)||0)?b:a);const prior=previousFor(e.name);if(prior&&Number(best.weight)>Number(prior.weight||0))prs.push(`${e.name}: +${Number(best.weight)-Number(prior.weight)} lb`);const ratings=completed.map(s=>s.rpe).filter(Boolean);const lastRpe=ratings.at(-1)||'right';const session={weight:Number(best.weight)||0,reps:Number(best.reps)||0,sets:completed.length,lastRpe,date:nowISO(),volume:completed.reduce((t,s)=>t+(Number(s.weight)||0)*(Number(s.reps)||0),0)};const priorSessions=historyFor(e.name);state.exerciseHistory[e.name]=[session,...priorSessions].slice(0,30)}});const note=prs.length?`New personal record: ${prs[0]}`:completedSets?`Coach recorded ${completedSets} completed sets and will adjust your next targets.`:'No completed sets were recorded.';state.coachNotes.unshift({date:nowISO(),text:note});state.workouts.unshift({id:p.id,title:p.title,focus:p.focus,date:nowISO(),minutes:Math.max(1,Math.round(elapsed/60)),volume,exercises:p.exercises.length,completedSets,prs});Object.keys(state.recovery).forEach(k=>state.recovery[k]=Math.min(100,state.recovery[k]+5));p.exercises.forEach(e=>{if(state.recovery[e.muscle]!=null)state.recovery[e.muscle]=Math.max(35,state.recovery[e.muscle]-25)});state.currentPlan=buildPlan('auto',state.settings.duration,7);saveState();renderAll();showView('homeView');$('#summaryVolume').textContent=`${Math.round(volume).toLocaleString()} lb`;$('#summarySets').textContent=completedSets;$('#summaryCoach').textContent=note;$('#workoutSummaryDialog').showModal()}
function renderProgress(){const measurements=state.measurements.slice(0,8);$('#measurementList').innerHTML=measurements.length?measurements.map(m=>`<div class="history-item"><div><strong>${m.weight||'—'} lb · ${m.fat||'—'}% fat</strong><span>${new Date(m.date).toLocaleDateString()}${m.waist?` · Waist ${m.waist} in`:''}</span></div><span>${m.steps?`${m.steps} steps`:''}</span></div>`).join(''):'<p>No measurements saved yet.</p>';$('#workoutHistory').innerHTML=state.workouts.length?state.workouts.slice(0,12).map(w=>`<div class="history-item"><div><strong>${w.title}</strong><span>${new Date(w.date).toLocaleDateString()} · ${w.minutes} min · ${w.completedSets||0} sets</span></div><span>${Math.round(w.volume||0).toLocaleString()} lb</span></div>`).join(''):'<p>No completed workouts yet.</p>';$('#coachHistory').innerHTML=state.coachNotes.length?state.coachNotes.slice(0,8).map(n=>`<div class="history-item"><div><strong>Coach Jorge</strong><span>${new Date(n.date).toLocaleDateString()}</span></div><span>${n.text}</span></div>`).join(''):'<p>Complete a workout to receive personalized coaching.</p>'}
function renderAll(){renderHome();renderPlan();renderProgress()}
function saveProfile(fromSetup=true){const src=fromSetup?'setup':'settings';state.profile=state.profile||{};state.profile.name=$(`#${src}Name`).value.trim()||'Jorge';state.profile.gym=$(`#${src}Gym`).value.trim();if(fromSetup){state.profile.age=Number($('#setupAge').value);state.profile.height=$('#setupHeight').value;state.profile.goal=$('#setupGoal').value;state.settings.days=Number($('#setupDays').value);state.settings.jointFriendly=$('#setupJoint').checked}else{state.settings.duration=Number($('#settingsDuration').value);state.settings.days=Number($('#settingsDays').value);state.settings.jointFriendly=$('#settingsJoint').checked}state.currentPlan=buildPlan();saveState();renderAll()}
function openSettings(){$('#settingsName').value=state.profile?.name||'Jorge';$('#settingsGym').value=state.profile?.gym||'';$('#settingsDuration').value=state.settings.duration;$('#settingsDays').value=state.settings.days;$('#settingsJoint').checked=state.settings.jointFriendly;$('#settingsDialog').showModal()}
let calculatedBodyFat=null;
function openBodyFatCalculator(){
  const savedWaist=$('#waistInput').value||state.measurements[0]?.waist||'';
  $('#bodyFatWaist').value=savedWaist;
  $('#bodyFatResult').hidden=true;
  $('#useBodyFatResultBtn').hidden=true;
  calculatedBodyFat=null;
  $('#bodyFatDialog').showModal();
}
function bodyFatCategory(value,sex){
  const ranges=sex==='female'?[ [14,'Essential fat'],[21,'Athletic range'],[25,'Fitness range'],[32,'Average range'],[Infinity,'Above average range'] ]:[ [6,'Essential fat'],[14,'Athletic range'],[18,'Fitness range'],[25,'Average range'],[Infinity,'Above average range'] ];
  return ranges.find(([limit])=>value<limit)?.[1]||'';
}
function calculateBodyFat(){
  const sex=$('#bodyFatSex').value;
  const feet=Number($('#bodyFatFeet').value), extraInches=Number($('#bodyFatHeightInches').value);
  const height=feet*12+extraInches, neck=Number($('#bodyFatNeck').value), waist=Number($('#bodyFatWaist').value), hip=Number($('#bodyFatHip').value);
  if(!height||!neck||!waist)return alert('Enter your height, neck, and waist measurements.');
  if(sex==='male'&&waist<=neck)return alert('Waist must be larger than neck for this formula.');
  if(sex==='female'&&(!hip||waist+hip<=neck))return alert('Enter a valid hip measurement.');
  let result=sex==='male'
    ?86.010*Math.log10(waist-neck)-70.041*Math.log10(height)+36.76
    :163.205*Math.log10(waist+hip-neck)-97.684*Math.log10(height)-78.387;
  if(!Number.isFinite(result)||result<2||result>70)return alert('Those measurements produced an unusual result. Please measure again and verify the numbers.');
  calculatedBodyFat=Math.round(result*10)/10;
  $('#bodyFatResult').innerHTML=`<strong>${calculatedBodyFat}%</strong><span>Estimated body fat · ${bodyFatCategory(calculatedBodyFat,sex)}</span>`;
  $('#bodyFatResult').hidden=false;
  $('#useBodyFatResultBtn').hidden=false;
}
function useBodyFatResult(){
  if(calculatedBodyFat==null)return;
  $('#bodyFatInput').value=calculatedBodyFat.toFixed(1);
  if($('#bodyFatWaist').value)$('#waistInput').value=$('#bodyFatWaist').value;
  $('#bodyFatDialog').close();
}

function saveMeasurement(){const m={date:nowISO(),weight:$('#weightInput').value,fat:$('#bodyFatInput').value,waist:$('#waistInput').value,steps:$('#stepsInput').value};if(!m.weight&&!m.fat&&!m.waist&&!m.steps)return alert('Enter at least one measurement.');state.measurements.unshift(m);saveState();['#weightInput','#bodyFatInput','#waistInput','#stepsInput'].forEach(x=>$(x).value='');renderProgress()}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`jorgefit-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(file){const r=new FileReader();r.onload=()=>{try{state={...structuredClone(defaultState),...JSON.parse(r.result)};saveState();renderAll();alert('Backup imported successfully.')}catch{alert('That backup file is not valid.')}};r.readAsText(file)}
function initEvents(){$$('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#settingsBtn').onclick=openSettings;$('#saveSetupBtn').onclick=()=>saveProfile(true);$('#saveSettingsBtn').onclick=()=>saveProfile(false);$('#startWorkoutBtn').onclick=()=>startWorkout(state.currentPlan);$('#regenerateBtn').onclick=()=>{state.currentPlan=buildPlan();saveState();renderAll()};$('#energyInput').oninput=e=>$('#energyValue').textContent=`${e.target.value}/10`;$('#buildPlanBtn').onclick=()=>{state.currentPlan=buildPlan($('#focusSelect').value,$('#timeSelect').value,$('#energyInput').value);saveState();renderPlan();renderHome()};$('#startGeneratedBtn').onclick=()=>startWorkout(state.currentPlan);$('#exitWorkoutBtn').onclick=()=>{if(confirm('Pause this workout and return home?')){clearInterval(timerId);showView('homeView')}};$('#finishWorkoutBtn').onclick=finishWorkout;$('#addExerciseBtn').onclick=()=>{const name=prompt('Exercise name');if(name){state.currentPlan.exercises.push(hydrateExercise({name,muscle:'Custom',sets:3,reps:'10-12',note:'Custom exercise',logged:Array.from({length:3},()=>({weight:'',reps:'',done:false}))}));renderActive()}};$('#minusRestBtn').onclick=()=>{restSeconds=Math.max(0,restSeconds-15);updateRest()};$('#plusRestBtn').onclick=()=>{restSeconds+=15;updateRest()};$('#skipRestBtn').onclick=()=>{clearInterval(restId);$('#restDialog').close()};$('#saveMeasurementBtn').onclick=saveMeasurement;$('#openBodyFatCalculatorBtn').onclick=openBodyFatCalculator;$('#closeBodyFatCalculatorBtn').onclick=()=>$('#bodyFatDialog').close();$('#calculateBodyFatBtn').onclick=calculateBodyFat;$('#useBodyFatResultBtn').onclick=useBodyFatResult;$('#bodyFatSex').onchange=e=>{$('#bodyFatHipRow').hidden=e.target.value!=='female';$('#bodyFatResult').hidden=true;$('#useBodyFatResultBtn').hidden=true};$('#clearHistoryBtn').onclick=()=>{if(confirm('Delete workout history?')){state.workouts=[];saveState();renderAll()}};$('#exportDataBtn').onclick=exportData;$('#importDataInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('#resetAppBtn').onclick=()=>{if(confirm('Reset all JorgeFit data? This cannot be undone.')){localStorage.removeItem(STORE);location.reload()}};$$('[data-action]').forEach(b=>b.onclick=()=>quickAction(b.dataset.action));$('#installBtn').onclick=installApp;$('#closeInstallBtn').onclick=()=>$('#installDialog').close();$('#closeReplacementBtn').onclick=()=>$('#replacementDialog').close();$('#closeExerciseInfoBtn').onclick=()=>$('#exerciseInfoDialog').close();$('#closeWorkoutSummaryBtn').onclick=()=>$('#workoutSummaryDialog').close()}
function quickAction(a){if(a==='quick30'){state.currentPlan=buildPlan('auto',30,6);saveState();renderAll();startWorkout(state.currentPlan)}else if(a==='cardio'){state.currentPlan=buildPlan('cardio',30,6);saveState();renderAll();startWorkout(state.currentPlan)}else if(a==='mobility'){const groups=[...new Set((state.currentPlan?.exercises||[]).map(e=>e.muscle))];const routine=groups.map(g=>{const m=muscleInfo(g);return `${g}: ${m.stretch} (${m.hold})`}).join('\n');alert(`AI Coach mobility cooldown\n\n${routine||'Full-body mobility for 5 minutes'}\n\nMove gently and stop if you feel pain.`)}else installApp()}
async function installApp(){if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else{$('#installInstructions').textContent=/iphone|ipad|ipod/i.test(navigator.userAgent)?'On iPhone: open this site in Safari, tap the Share button, choose “Add to Home Screen,” then tap Add.':'Open your browser menu and choose “Install app” or “Add to Home screen.”';$('#installDialog').showModal()}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});
function connection(){const off=!navigator.onLine;$('#offlineBanner').hidden=!off}
window.addEventListener('online',connection);window.addEventListener('offline',connection);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.error));
initEvents();renderAll();connection();if(!state.profile)$('#setupDialog').showModal();
